### ISSUE TITLE
Small issues on master

### ISSUE THREAD

**Issue by ja2-derek** [ja2-stracciatella/ja2-stracciatella#1127]
Tracking small, non-blocker issues I found on current master. Some are related to my recent PRs. I will keep updating this.

- [x] Log says "externalized/DefaultContentManager.cc: Unsupported file type." when it is actually a directory not found. (#1131)
- [x] The title of the IMP Skills Trait screen is a few pixels too high. See this [screenshot](https://user-images.githubusercontent.com/63151803/85189813-bf4cf200-b2e4-11ea-852e-ba2656b6388c.png) (#1130)
- [x] (Editor, 0.16.1) Unnamed placeholder items towards the ends of AMMO and WEAPONS lists in Editor. Those are the `CLIP_NOTHING` in `magazines.json` and `unused` in `weapons.json` (#1191)
- [x] IMP Skill Traits introduced a couple of "high impact" defects on Coverity  (#1190)
- [x] Compiler warning:
    - [x] Missing `()` in function call: https://github.com/ja2-stracciatella/ja2-stracciatella/pull/1174/commits/a1d2919104d4c6c3e72cf62d874d12d828a89888#diff-60d1ebf19ff040db3da437082175c7feR1153   (#1190)
- [x] If JSON has a missing data field or field contains an unexpected data type, logs only say "Assertion failed: false, ... rapidjson/document.h, line 1053", without mentioning which JSON file or which field. (#1133, #1167)

**Comment by lynxlynxlynx** [comment]
Forgot about this, but I'm working on tackling the last item for game.json parsing.

**Comment by lynxlynxlynx** [comment]
For the last item, missing keys are now taken care of, but invalid values still assert.
