### ISSUE TITLE
0.18 checklist

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#1331]
Just a copy from 0.17 to be adapted as we go. We've done a lot of work already (99 closed issues in the milestone), so after some of the dangling PRs are finished, we could easily make another release already.

- [x] Fix or postpone issues in the [milestone](https://github.com/ja2-stracciatella/ja2-stracciatella/milestone/4)
- [x] Decide if 0.18 should be 1.0 #443 
- [x] Triage open pull requests
- [x] Finalise choice of version number
- [x] Update Version number
- [x] Github prerelease and tags
- [x] Attach built versions to release
  - [x] Linux, Windows
  - [x] OS X
- [x] Runtime tests of release packages
  - [x] Linux
  - [x] Windows
  - [x] OS X
- [x] Add new contributors to contributors.txt #1151 
- [x] Update changes.md #1153
- [x] Document any new features
  - [x] https://ja2-stracciatella.github.io/features/
  - [x] https://ja2-stracciatella.github.io/how-to-run/#extra-configuration-and-modding
- [x] Make prerelease the release
- [x] reset version to +1-dev
- [x] Announce
  - [x] Write main announcement
  - [x] Website
  - [x] Bears pit
  - [x] Moddb

**Comment by ja2-derek** [comment]
Nightly builds here: https://github.com/ja2-stracciatella/ja2-stracciatella/actions?query=branch%3Anightly

**Comment by selaux** [comment]
Yeah. I guess it makes sense to create a new release by now.

Looking at the milestone, I think big new features are:
- Modding improvements
  - Several hardcoded values and assumptions are now externalized to json files for easy editing (SAM sites, Items, M.E.R.C. soldiers, Sector Land Types, Weapon Cache Location)
  - Initial scripting support via lua scripts
  - Supporting Unfinished Business tilesets
  - Support for ogg and mp3 audio formats
- AppImage for linux builds

Regarding Android I think it does not make sense to include the build into 0.18.0 as touch controls just dont work properly (and looking at the mouse handling code I think it will take some time to implement touch properly).

**Comment by lynxlynxlynx** [comment]
I wouldn't complicate matters for android — let's just not spotlight the work and leave it as is, inviting contributors. SDL2 has separate events for touch, so we need to bind something to get right-click (maybe two-finger press?) as a minimum.

**Comment by ja2-derek** [comment]
Tried building on a fresh install of Windows and VS 2019, noted a few things:

- The build requires Widows 8 SDK which is already deprecated with VS 2019. It seems to be required by some of our deps.
- Visual C++ 2015 (`v140`) re-dist package is required
- `gtest` asks for Python but this is not mentioned in docs

I have started a play-through with master build (8662268) on Win10, into the 60th in-game day, already gone through the basics (Drassen airport, Bobby Ray, etc). I haven't found any new blocker problems. But I did ran into a few minor and occasional issues some of which I cannot yet confirm or re-produce:

- Occasionally enemy getting stuck at running state (#1319)
- Enemy completely disappear from tactical LoS but still flagged in bottom pane and mini-map. Then they suddenly reappear when they attack. Not able to reproduce.
- Queen's Army patrolling into San Mona C6 in early game when Kingpin was alive. Not sure if it is a bug or not.
- Some warning and error logs, but none seem to impact the game:
    - `[ERROR] game\Tactical\ShopKeeper_Interface.cc: Assertion failed in D:\Workspace\ja2-stracciatella\src\game\Tactical\ShopKeeper_Interface.cc, line 5840`
    - `game\Tactical\ShopKeeper_Interface.cc: Assertion failed in D:\Workspace\ja2-stracciatella\src\game\Tactical\ShopKeeper_Interface.cc, line 550:
Selected merc can't interact with shopkeeper.  Send save AM-1`
    - `[ WARN] game\TileEngine\Structure.cc: Structure is not defined` -- I am on Vanilla maps, GOG version
    - `[ERROR] sgp\SoundMan.cc: SoundLoadDisk Error: pFilename is an empty string.`  -- happens when entering B13 Drassen airport 
- "Long-click" resulting in bursting the primary weapon (accidentally killed Fatima)  - reported in #1184

**Comment by lynxlynxlynx** [comment]
That's quite a good outcome, considering the amount of changed things.

**Comment by ja2-derek** [comment]
Are we good for 0.18 now? @selaux  - should we push https://github.com/ja2-stracciatella/ja2-stracciatella/pull/1275 and the related issues to later?

**Comment by selaux** [comment]
I guess so, I currently don't see me finishing this soon...

**Comment by lynxlynxlynx** [comment]
Ok then. I'll move them forward to the new milestone and get about finishing the texts.

**Comment by lynxlynxlynx** [comment]
Done: changes and contributors, announcement, site update (just added the extra hotkey).

I'll do some testing in the following days.

**Comment by selaux** [comment]
I updated the version number and created a prerelease. Lets see if the binaries are built correctly.

**Comment by lynxlynxlynx** [comment]
Thanks. Mac failed, but perhaps just a quota thing, since it was a fetch failure.

The appimage game works. :)

The editor quits soon after starting though:
```
2021-04-21T19:27:13 [ INFO] game/Editor/EditScreen.cc: Entering editor mode...
2021-04-21T19:27:13 [ERROR] sgp/SGP.cc: Game has been terminated due to an unrecoverable error: openGameResForReading: VfsFile_open "editor/invpanel.sti": entity not found
Creating an emergency savegame failed.
Please report this error with a description of the circumstances. (St13runtime_error
2021-04-21T19:27:14 [ERROR] launcher/Launcher.cc: Command_execute "/tmp/.mount_ja2-stiI350f/usr/bin/ja2" ["-editor"]: terminated by a signal
```

**Comment by lynxlynxlynx** [comment]
Tested up to full Drassen capture; nothing else popped up. :)

**Comment by lynxlynxlynx** [comment]
Looks like it's time for a retag and finishing this up. 👍🏾

**Comment by selaux** [comment]
I tested as well until Drassen capture on Linux and played some more on macOS. I didn't find anything big as well. A small thing I noticed was a noticeable lag after ending the players turn and noticeable lags while enemy turn was executed. Not sure if that is a new thing though, or if it has always been that way.

I also tested the AppImage execution on multiple systems:

- Current Manjaro Linux: Works
- Ubuntu 18.04: Works
- Fedora 33: Works
- Debian Buster (Stable): Does not work, libstdc++ version seems too old. I wouldn't consider stable Debian a must-have though...

Retagged to the current master. Builds are in progress...

**Comment by lynxlynxlynx** [comment]
Can't say I notice any end of turn lag myself.

**Comment by lynxlynxlynx** [comment]
All is well with the new appimage, so I'll go update the page.

**Comment by lynxlynxlynx** [comment]
I was feeling lucky, so just went ahead and finished the whole thing. I'm positive the windows version still works. :)

Thank you both and in particular Derek with your continued externalization work! 🔥

**Comment by ja2-derek** [comment]
Windows build (x64 build on Win10) is working fine for me so far.
