### ISSUE TITLE
0.20 release checklist

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#1680]
Copying the template from docs/

## Pre-release development

- [x] Fix or postpone issues in the [milestone](https://github.com/ja2-stracciatella/ja2-stracciatella/milestone/8)
- [x] Triage open pull requests and recent bugs
- [x] Finalise choice of version number
  - [x] Decide if this version should be 1.0 #443 
- [x] Add new contributors to contributors.txt
- [x] Update changes.md (run docs/draft-changelog.sh to get started)
- [x] Update man page if necessary

## Release candidate

- [x] Update Version number to `-rc` and tag
- [x] Mark the tag as a Github prerelease
- [x] Runtime tests of prerelease packages
  - [x] Linux
    - [ ] Ubuntu 20.04 x64
  - [x] Windows
  - [ ] OS X
  - [x] Android
  
Runtime tests:
 * IMP creation
 * AIM and extending contracts
 * taking Drassen airport or more
 * buying from Bobby Ray's
 * visual inspection of laptop screens

If you want to build the packages manually:

    $ make clean
    $ make build-releases # to build all releases
    $ make build-win-release-on-linux # crosscompile Windows release on Linux
    $ make build-release-on-mac # build the mac bundle
    $ make build-debian-package # build the .DEB package

# Release

- [x] Attach built versions to GitHub release
  - [x] Linux, Windows
  - [x] OS X
  - [x] Android
- [x] Document new features on the website
- [x] Make GitHub prerelase the release, update texts
- [x] Announce
  - [x] Write main announcement
  - [x] Website download page (update frontmatter variables as needed)
  - [x] Website news
  - [x] Bear's pit
  - [x] Moddb

  
## Post-release
- [x] Set version to +1 and add the `-dev` suffix
- [x] Close this bug and GitHub milestone
- [x] Create new milestone if none exists yet

**Comment by selaux** [comment]
All of the items of the milestone are resolved. Any other issues that we should have a look at before the release?

**Comment by lynxlynxlynx** [comment]
I think we're ready to go. There are some assertion bugs open, but without reproducers.

**Comment by selaux** [comment]
I tagged `v0.20.0`. Release candidate packages are here for testing: https://storage.googleapis.com/ja2-builds/index.html#releases/v0.20.0/

**Comment by lynxlynxlynx** [comment]
Did the standard test and all seems fine. :)

Two oddities that I noticed:
- you can't exit Omerta to the south; no idea if that is new, the cursor just doesn't switch to the travel one
- the aiming cursor almost flickers when you decide to shoot; it goes through a few modes rapidly. Also not sure if it's new, but ideally we wouldn't show the outer aiming circle any more until the shooting is done

**Comment by selaux** [comment]
I am still not quite done with testing (mostly on Android), but so far everything looks fine here as well. I've prepared the release announcement here: https://github.com/ja2-stracciatella/ja2-stracciatella.github.io/pull/12.

@lynxlynxlynx The exiting from Omerta to the South I would like to investigate before the release. It's probably a result of the touch changes and might affect other sectors as well. And it would probably be quite annoying if the player wants to flee from a sector. I have the feeling the scrolling code does not really behave the same on different resolutions / different ways of scrolling. What resolution are you playing in?

I've noticed the flickering of the aiming cursor as well. It's probably a result of the touch control changes as well. But I wouldn't call this a release blocker.

**Comment by lynxlynxlynx** [comment]
It don't remember, but probably the launcher default (1024x768?).

**Comment by selaux** [comment]
I'm done with testing on Android. The controls are a little glitchy sometimes (especially scrolling), but I had no real issues playing it on my tablet. For phones there might still be issues with the controls being too small, but that's something to improve in the future.

**Comment by selaux** [comment]
Do we still want to test Windows and macOS? Or do we assume it just works?

**Comment by lynxlynxlynx** [comment]
Windows deserves at least some basic testing, since that's what most of our users are on.

**Comment by ja2-derek** [comment]
I no longer have my Windows desktop. I have just tried the basics on a Windows Server. I did a fresh install, ran the game till the rebel basement. Everything is fine except some unrelated WARN logs.

**Comment by lynxlynxlynx** [comment]
Good enough for me. :)

**Comment by selaux** [comment]
Tag has moved to current master. New release packages are built: https://storage.googleapis.com/ja2-builds/index.html#releases/v0.20.0/

**Comment by lynxlynxlynx** [comment]
If that was hiding a question, it still runs for me. :)

**Comment by selaux** [comment]
... and now it's released. Website announcement and downloads are up! Announcement in Discord has been done as well.
