### ISSUE TITLE
0.21 release checklist

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#1909]
Copying the template from docs/

# Release Checklist

## Pre-release development

- [ ] Fix or postpone issues in the [milestone](https://github.com/ja2-stracciatella/ja2-stracciatella/milestone/10)
- [ ] Triage open pull requests and recent bugs
- [x] Finalize choice of version number
  - [x] Decide if this version should be 1.0 #443
- [ ] Add new contributors to contributors.txt
- [ ] Update changes.md (run docs/draft-changelog.sh to get started)
- [ ] Update man page if necessary

## Release candidate

- [ ] Update Version number to `-rc` and tag
- [ ] Mark the tag as a Github prerelease
- [ ] Runtime tests of prerelease packages
  - [ ] Linux
    - [ ] Ubuntu 20.04 x64
  - [ ] Windows
  - [ ] OS X

Runtime tests:

- IMP creation
- AIM and extending contracts
- Taking Drassen airport or more
- Buying from Bobby Ray's
- Visual inspection of laptop screens

If you want to build the packages manually:

    $ make clean
    $ make build-releases # to build all releases
    $ make build-win-release-on-linux # crosscompile Windows release on Linux
    $ make build-release-on-mac # build the mac bundle
    $ make build-debian-package # build the .DEB package

## Release

- [ ] Attach built versions to GitHub release
  - [ ] Linux, Windows
  - [ ] OS X
- [ ] Document new features on the website
- [ ] Make GitHub prerelease the release, update texts
- [ ] Announce
  - [ ] Write main announcement
  - [ ] Website download page (update frontmatter variables as needed)
  - [ ] Website news
  - [ ] Bear's pit
  - [ ] Moddb

## Post-release

- [ ] Set version to +1 and add the `-dev` suffix
- [ ] Close this bug and GitHub milestone
- [ ] Create new milestone if none exists yet

**Comment by lynxlynxlynx** [comment]
Ok, so I guess that's it then and we can just do the final testing before the rest of the steps.

**Comment by selaux** [comment]
The release candidate has been tagged and builds should show up here: https://storage.googleapis.com/ja2-builds/index.html#releases/v0.21.0-rc1/

**Comment by lynxlynxlynx** [comment]
Did the usual testing just beyond Drassen and all seems fine.

**Comment by momoko-h** [comment]
I believe the fix in #1920 should be in 0.21, that's a highly visible and relatively easy to trigger new bug.

**Comment by selaux** [comment]
I also did some testing on Android, continuing my current game I have on my tablet. Haven't encountered anything obvious. I also tested running on macOS, but also didn't do the usual playtest there.

**Comment by lynxlynxlynx** [comment]
I think we can just retag and prepare the final builds then. I'll go update the changelog with the last few fixes.

**Comment by selaux** [comment]
Builds are done. Website is done. Announcement on the Bears Pit Discord is done. Missing is the Bears Pit Forum and ModDB, I have no credentials for those.

**Comment by lynxlynxlynx** [comment]
Done. Good job everyone! 👍🏾

**Comment by selaux** [comment]
Thanks everyone involved :slightly_smiling_face:.

@misanthropos Care to build another ARM AppImage?

**Comment by misanthropos** [comment]
It is done! Anything else? :-)
