### ISSUE TITLE
[master bug] viewport/placement related bugs

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#225]
To limit confusion between the similar reports, I opened a new meta bug.

Here is the gist:
- [x] #171 we show one grid line (diagonal) at the bottom too many, one too much at the top
  - this potentially affects #73 too
- [x] #195 npcs at the top row can't be targetted for headshots
- [x] #125  enemies (all npcs?) can get placed on inaccessible squares
- [x] #119 glitches while scrolling

**Comment by derSteFfi** [comment]
now that you put it out that way, sounds like an off-by-one in the area to draw to me?

**Comment by lynxlynxlynx** [comment]
I'm investigating. Is just the viewport wrongly positioned, the accessibility mask (let's pretend  that exists) or both? I think all this came to be after a refactoring in 2013.

**Comment by JAsmine-ja2** [comment]
Great to see this issue(s) getting investigated. This is imo one of the two most annoying issues with Stracciatella atm.

**Comment by derSteFfi** [comment]
right now, i see two parts here:
1. We most certainly have an off-by-one somewhere (as mentioned earlier)
2. I think we have a general problem with the way we handle scaling. In Vanilla, due to the fixed resolution, the ratios of the tactical map, the squad overview, radar screen, etc. where fixed. We sclae the tactical view up, making x:y-ratio variable. This is worked around in many places, but most of the time (at least from what I saw so far) by introducing scaling factors and rounding results back to full pixels. This works for most places, but e.g. #73 and #119 could be a symptom of that. My only solution right now is to scale the tactical only with fixed x:y-ratio. We get black sections of the screen then, but we also have them where we can't scale things up (main menu, right of the radar screen, etc.)

Maybe the best way is to sort out the off-by-one first and investigate all the other issues again afterwards.

**Comment by selaux** [comment]
:+1: Maybe there is some integer division happening somewhere. Can you point to the place in code where the viewport is scaled?

**Comment by derSteFfi** [comment]
i saw it in RadarScreen.cc when fixing #73. During the process i grepped for 'scale' (aifair) to find some decleration and around 50 lines popped up where a vairable was named [g,f,ub,s]Scale[x,y]...

**Comment by lynxlynxlynx** [comment]
There is integer division happening, for example in the part I'm looking at for the viewport bit, but it's only for rounding to a multiple of cell size. No use of parentheses, so I hope it doesn't break in release builds (the pattern is just x / y * y).

Jasmine: what's the other one?

**Comment by JAsmine-ja2** [comment]
The 2nd of the two most annoying issues atm is #78 .

**Comment by derSteFfi** [comment]
maybe #170 is also a symptom of this?

**Comment by lynxlynxlynx** [comment]
That one only affects the maxi-minimap. We don't clip to the area frame.

**Comment by selaux** [comment]
A new update from my side: I tried to revert some changes, that were done to scrolling, namely [this commit](https://github.com/ja2-stracciatella/ja2-stracciatella/commit/d3800c3544c82edb14d5b0fc9bc1c4eb854e47f1). This seemed to fix the issue with the incorrectly shown bottom tiles and missing top tiles. You can see this in this imgur album comparing ja2-s, vanilla and the version after the revert: http://imgur.com/a/5gGs7.

The problem is: I'm bot sure what this commit actually did, e.g. what counts as a small map and how they improved the rendering. Also not sure whether enemies can still spawn outside of view.

**Comment by selaux** [comment]
Maybe @gennady can show some insights on what the commit actually did. I pushed the changes to the `fix-171-showing-too-many-tiles` branch.

**Comment by JAsmine-ja2** [comment]
Small maps are maps like the rebel's underground hideout a10_b1.

**Comment by selaux** [comment]
Allright, I tested a run until recruiting Ira and there were two issues that popped up:
- Scrolling is broken on small maps (rebel hideout)
- Initial camera position is broken when entering Omerta the first time, which also doesnt let you scroll

Maybe we can fix them in a different way.

**Comment by lynxlynxlynx** [comment]
Hmm, that's odd. It was the first thing I looked at and bisection led me straight past. I've had almost no time the past week, but reverting just parts didn't bring me any closer to the culprit.

**Comment by derSteFfi** [comment]
OK, i started to poke around this too. i was able to better the situation for hte top on current master by changing
```C
BOOLEAN fOutTop    = (gsTLY >= sTopLeftWorldY);
```
to
```C
BOOLEAN fOutTop    = (gsTLY > sTopLeftWorldY);
```
In RenderWorld:ApplyScrolling (the commit mentioned by @selaux)
There is still one row missing at the top and too much at the bottom, but this seems like a part way...

**Comment by derSteFfi** [comment]
OK, not sure if this is related, but i noticed the following:
when starting at the top left, scrolling down and/or right and pressing ALT before releasing the arrow keys to stop the world from getting fully rerendered, i noticed an off-by-on glitch:
![offbyone](https://cloud.githubusercontent.com/assets/9593455/14013841/0eb76326-f1af-11e5-9494-09036431a38a.jpg)

follow left and/or up from the red dot to see it. This only happens when starting somewhere top left, not sure about the limits of the starting point right now but I suspect the rendercenter needs to be within 640x480. this is corrected as soon as the ALT key is released by shifting the top left on row to the top and to the left. Obviously, the srolled in rows and columns are calculated different than the already shown ones. As said, not sure this is related here...

**Comment by JAsmine-ja2** [comment]
I can definitely say, that I've observed this behavior as well.
I'm quite sure that this error can also be triggered by other means, but I'm not sure, how.

**Comment by selaux** [comment]
Why do we do tilewise scrolling anyway? Imho this is not necessary. We could quickfix as many issues as we can for the current release and rewrite the whole thing to do smooth scrolling for the next one.

**Comment by lynxlynxlynx** [comment]
Ok, I see now where the discrepancy was. I was looking at 195 and for that one the revert is not enough. Since the reverted screenshots match the original, I checked the original and it turns out this headshotting problem is not a regression at all. :)

**Comment by JAsmine-ja2** [comment]
I compared a specific situation in Vanilla JA2 and in Stracciatella:

# Situation 1: Sector A2, scrolled to the top-right corner as much as possible. 640x480 resolution. The merc went to the topmost tile.
![1-stracc](https://user-images.githubusercontent.com/17213795/34651166-e702bf0c-f3cc-11e7-930b-0e36fac7ac6c.jpg)
![1-vanilla](https://user-images.githubusercontent.com/17213795/34651167-e724baee-f3cc-11e7-93f0-da87a7c4fd2f.jpg)

When looking at the pillar next to the merc or the bushes/trees east of the merc, it's obvious that the Stracciatella version allows to scroll and walk one extra row to the top.

# Situation 2: Sector A2, scrolled to the lower-right corner as much as possible. 640x480 resolution. The merc went to the downmost tile.
![2-stracc](https://user-images.githubusercontent.com/17213795/34651168-e748e90a-f3cc-11e7-8f9e-c3f637c7549a.jpg)
![2-vanilla](https://user-images.githubusercontent.com/17213795/34651169-e76d1e56-f3cc-11e7-8efb-05c8d0dc2a27.jpg)

When looking at the trees to the right, it's obvious that the Stracciatella version shows 2 extra rows to the south, but doesn't allow the merc to walk further down compared to vanilla.

**Comment by chmallon** [comment]
> When looking at the pillar next to the merc or the bushes/trees east of the merc, it's obvious that the Stracciatella version allows to scroll and walk one extra row to the top.

Don't you mean 'vanilla' instead of 'stracciatella' here?
The vanilla screenshot shows one more row at the top.

**Comment by JAsmine-ja2** [comment]
Yes, I corrected it. Thx!

**Comment by chmallon** [comment]
> OK, not sure if this is related, but i noticed the following:
> when starting at the top left, scrolling down and/or right and pressing ALT before releasing the arrow keys to stop the world from getting fully rerendered, i noticed an off-by-on glitch:

This is a vanilla bug.
It only happens in the upper right corner when scrolling to the right.
Most of the screen is just copied to the left and only the small strip at the right is rendered.
When calculating the (world) coordinates for rendering it gets negative and this gets handled wrong.
The bug is in CalcRenderParameters().
Basically the problem is that division rounds towards zero, what they actually need is rounding towards minus infinity, but the correction they do is wrong. 

This is one of the many problems in the scrolling and rendering code.

**Comment by chmallon** [comment]
> Yes, I corrected it. Thx!

Did you try bisecting to find out, which commit introduced the behavior?
AFAICT this behavior was not introduced by me.

There are a lot of magic offset calculations in the scrolling and rendering code.
One of the most funny ones is is the pair gsRenderWorldOffsetX/gsRenderWorldOffsetY.

**Comment by JAsmine-ja2** [comment]
![screen000](https://user-images.githubusercontent.com/17213795/34685792-d57e84ea-f4a9-11e7-96ff-7f59911032d9.jpg)
![screen001](https://user-images.githubusercontent.com/17213795/34685793-d59d735a-f4a9-11e7-9a93-021a99c91827.jpg)

This must have been introduced in the very beginning of the first "JA2 Stracciatella continued" phase on Bitbucket or earlier.
This buggy behavior is already present in 0.12.175 or earlier.

**Comment by lynxlynxlynx** [comment]
So is this recap accurate?
Top: 1 line of display and accessibility missing
Bottom: 2-3 lines of extraneous display; accessibility is fine

There's more discussion in #171 (this being a meta bug), but some of the findings may be old by now.

**Comment by JAsmine-ja2** [comment]
I did a thorough test and present my findings in #171
