### ISSUE TITLE
[master bug] AP related bugs

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#231]
For a better overview:

- [ ] #192 attack for 0 AP 
- [ ] #191 stealing
- [ ] #190 disappearing APs
- [ ] #186 knife throwing
- [ ] #188 turning to unseen enemies
- [ ] likely #194 (partly an enchancement)

**Comment by JAsmine-ja2** [comment]
Should #376 be added to this list?

**Comment by lynxlynxlynx** [comment]
No, that's _merely_ a drawing issue.

**Comment by Manuel-K** [comment]
@daviel: Do you think you will be able to fix your three PRs related to the remaining issues this month?

Otherwise I'd suggest bumping the rest to the next version.

**Comment by daviel** [comment]
@Manuel-K I can't tell for sure that I will be able to solve the problems in november but I will try to. Will give feedback within the next 7 days. 👍

**Comment by Manuel-K** [comment]
@daviel Thank you.
