### ISSUE TITLE
0.16 release notes and checklist

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#437]
Since some random stuff piled up, I'm opening this early.

Some of you probably noticed already, but I add all new features and non-dev regression fixes to the current milestone (either the bugs or their PRs). That way generating a changelog and docs will be much easier, since the list of candidates is always up to date. Large merges like the logging rework make the old approach of reviewing git log unwieldy, but the milestone approach doesn't have that problem.

To me, our changelog would ideally have several sections: vanilla bugs fixed (key selling point), our bugs fixed (from previous releases), new features (including just externalised stuff), new content (bundled mods) and misc (for any that don't fit elsewhere). I've created a _vanilla_ and _non-vanilla_ tag, which we can label issues with in the future — @JAsmine-ja2, please take a look at [bugs](https://github.com/ja2-stracciatella/ja2-stracciatella/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20-label%3Anon-vanilla%20-label%3Aenhancement%20-label%3Aquestion%20-label%3Aproposal%20-label%3Atask) (list of all non-tagged) and tag as appropriate. We have almost 150 open bugs, but many are actually enhancement requests/wishes hidden as bugs from the original. Hopefully that doesn't scare anyone off. We could add a github bug reporting template, but I don't think non-team members can label issues.
- [x] Fix or postpone issues in the [milestone](https://github.com/ja2-stracciatella/ja2-stracciatella/milestone/2)
- [x] Triage open pull requests
- [x] Finalise choice of version number
- [x] Update Version number
- [x] Github prerelease and tags
- [x] Attach built versions to release
  - [x] Linux, Windows
  - [x] OS X
- [x] Runtime tests of release packages
  - [x] Linux
    - [x] Ubuntu 16.04 x64
  - [x] Windows
  - [x] OS X
- [x] Add new contributors to contributors.txt
- [x] Make prerelase the release
- [x] Document new features, at least:
  - [x] Dead is dead https://github.com/ja2-stracciatella/ja2-stracciatella/issues/308#issuecomment-256404182
  - [x] merged vxx goodies (new hotkeys, game.json) #307 and [site](https://github.com/ja2-stracciatella/ja2-stracciatella.github.io/issues/4)
    - [x] also link game.json somewhere general, directly
  - [x] new bundled mods (about 4)
  - [x] some notes about the launcher.
  - [x] copy README launcher docs here too: https://ja2-stracciatella.github.io/how-to-run/
- [x] Announce
  - [x] Mention that we automatically disable sound if SDL2 2.0.6 is detected + that we'll be using c++11 from then on
  - [x] Website
  - [x] Bears pit
  - [x] Moddb

**Comment by selaux** [comment]
Nice work. Adding the issues to the milestone is a very good idea, I was already thinking about how we could create the cangelog for 0.16.0 and this will make it a lot easier.

**Comment by JAsmine-ja2** [comment]
I'm not a collaborator and therefore can't edit labels.

**Comment by lynxlynxlynx** [comment]
What a tiny obstacle. :) If you didn't get a mail, follow this link: https://github.com/ja2-stracciatella/ja2-stracciatella/invitations

**Comment by JAsmine-ja2** [comment]
Thanks. I'm on it. :)

**Comment by lynxlynxlynx** [comment]
So, besides @daviel killing AP bugs with great persistence, we've mostly come to a lull. At the same time, **a lot** has already been done for 0.16, with not much remaining tagged on the milestone. Some of the stuff can be postponed, the retests probably closed and some of the fixes finalised (also reducing the open PR count). 

In other words, how about we make the release in November? I can commit also some dev time to make it happen.

https://github.com/ja2-stracciatella/ja2-stracciatella/milestone/2

**Comment by JAsmine-ja2** [comment]
100% pro this idea.

**Comment by selaux** [comment]
I also like the idea 👍 . I will try to reserve some time as well. We might need to look over the bugs once more and check whether there are issues that have been introduced after `0.15.1` and which are worth fixing.

**Comment by derSteFfi** [comment]
Also pro :)
Still having trouble finding time, but it should slowly improve again. We have a few bugs fixed, so a release doesn't hurt for sure.

**Comment by daviel** [comment]
Would love to see 0.16 released in november. I will effort some time soon to fix the ap bugs once and for all :)

**Comment by Manuel-K** [comment]
I'd like to merge the launcher in some form and ideally merge some of the formatting/indentation fixes as well.

**Comment by Manuel-K** [comment]
**Important**: Mention that we automatically disable sound if SDL2 2.0.6 is detected in the release notes.

**Comment by lynxlynxlynx** [comment]
draft of the release notes: https://gist.github.com/lynxlynxlynx/557e59497d8decdc3bc7757d12654acb

**Comment by Manuel-K** [comment]
Do gists support editing by multiple authors?

**Comment by lynxlynxlynx** [comment]
Don't know, it's the first one I ever created. Do you see an edit button at the top?

I can add it as a draft to the website repo otherwise.

**Comment by Manuel-K** [comment]
Only star, fork, embed, download zip.

**Comment by Manuel-K** [comment]
Can you see my fork?

**Comment by Manuel-K** [comment]
I don't think the ini is automatically converted to a JSON file. We don't use microini any more.

**Comment by lynxlynxlynx** [comment]
I can see it, but can't do anything about it. Eh well. Easily fixed once we're done with the code changes and it's time to do the last section.

**Comment by Manuel-K** [comment]
We need to update `ja2_manpage`, `assets/distr-files-mac/README.*.txt` and `assets/distr-files-win/README.*.txt`

**Comment by Manuel-K** [comment]
`assets/distr-files-win/README-SDL.txt` needs to be updated for SDL2

**Comment by lynxlynxlynx** [comment]
what man page changes did you have in mind?

**Comment by Manuel-K** [comment]
I think it should mention the launcher and suggest using it instead of manually editing `ja2.json`.

**Comment by Manuel-K** [comment]
I'd also change the ”RUSSIAN_GOLD is for Gold release.” to at least ”RUSSIAN_GOLD is for the Gold release.” or ”Use RUSSIAN_GOLD for Gold release.”

Analogous changes for RUSSIAN.

**Comment by lynxlynxlynx** [comment]
I disagree on the first point. It can't hurt to mention the launcher, but the 1 promiriad of our users that would even read the man page won't need to be told about how to edit files or avoid it through a separate app.

**Comment by Manuel-K** [comment]
There is `assets/distr-files-linux/ja2.6`, too. Do we really use both?

**Comment by Manuel-K** [comment]
Oops. I didn't update the date when i change `ja2.ini` to `ja2.json`.

**Comment by lynxlynxlynx** [comment]
Didn't even know we have two. The toplevel one doesn't have a standard name, but that's what's seen most updates.

**Comment by Manuel-K** [comment]
The one in assets is completely outdated, but it has some flavour text. I think we should replace it with the top level one (via `git mv`).

**Comment by lynxlynxlynx** [comment]
Sure, but keep the saner name.

Since progress stalled again, I propose we just go through with the release. Maybe that will spur someone with a mac to recheck those two bugs. The remaining AP bugs are not new either, so they can wait too (the throwing fix can be merged and the other half fixed later, but needs more testing).

**Comment by Manuel-K** [comment]
Do you have a script/automated way to gather all closed issues that are part of the milestone? 

I'll move the content of the gist to a PR tomorrow (OK, now it's today) – it seems the only way to edit a gist cooperatively is forking it again and again. Should I base it off this repo or the webpage?

**Comment by Manuel-K** [comment]
I've created a new milestone for the near future issues and moved the macOS stuff.

**Comment by lynxlynxlynx** [comment]
put it in the website repo, it'll be a news item anyway.

**Comment by selaux** [comment]
https://github.com/ja2-stracciatella/ja2-stracciatella/issues/485 should be part of `0.16` imho. As it will completely break the game for Russian Sierra users.

**Comment by lynxlynxlynx** [comment]
But is it a 0.15 regression or not? If not, there's no rush — only one person noticed it so far. We can always do a quick 0.16.1 if interest changes with the announcement.

**Comment by Manuel-K** [comment]
“Hello. I use the compiled version ja2-v0.15.1-macos from your site and watch just such a problem (see screenshots in the attachment) with fonts in some places.”

Does not seem to be a regression. I would call it a “known issue”.

The thing is – we could wait months if we consider it a blocker.

**Comment by Manuel-K** [comment]
New location of the changelog: https://github.com/ja2-stracciatella/ja2-stracciatella.github.io/pull/6

**Comment by selaux** [comment]
Yeah, also if there is no macOS developer it might even take longer... so I'm fine with it. Maybe it is fixed when compiling under Sierra as well...

**Comment by selaux** [comment]
What about builds? Do we want to build releases using travis or the old vms?

**Comment by lynxlynxlynx** [comment]
Up to you, since you've done it previously.

**Comment by selaux** [comment]
I would opt for travis. We would loose the Ubuntu i686 package though...

**Comment by Manuel-K** [comment]
@selaux @lynxlynxlynx @derSteFfi @JAsmine-ja2 Can everyone check my draft of the release notes?

Jaka, what does **TODO: docs** mean?

**Comment by lynxlynxlynx** [comment]
we don't have docs for game.json on our page yet.

As for the changelog, I'd group the items by category and somehow additionally tag resolved vanilla issues (subgroup?).

**Comment by Manuel-K** [comment]
Added (vanilla) to the category. Sorted by category.

I'm not happy with some of the texts, e.g. “Gas on a roof can damage the merc underneath the roof”. I'd prefer messages that indicate the improvement. The simplest fix would be adding fix at the beginning of each negative sentence, e.g. “Fix gas on a roof can damage the merc underneath the roof”.

**Comment by Manuel-K** [comment]
Done.

**Comment by JAsmine-ja2** [comment]
Concerning the draft of the release notes:
https://gist.github.com/lynxlynxlynx/557e59497d8decdc3bc7757d12654acb

- the now bundled mini-mods are more a proof of concept than relevant mods. I'm not sure if they're worth being mentioned as a feature.
- include a link to the mentioned nightly builds?

**Comment by Manuel-K** [comment]
@JAsmine-ja2 That version is very outdated. The new version is (currently) here: https://github.com/ja2-stracciatella/ja2-stracciatella.github.io/blob/changelog-0.16.0/Changelog-0.16.0.md

**Comment by derSteFfi** [comment]
the links to our own website don't seem to work if they link to chapter of the features page. all links to pages (e.g. to downloads) work though.

**Comment by lynxlynxlynx** [comment]
The titles got changed, that's why.

**Comment by lynxlynxlynx** [comment]
Can we get some extra eyes in #448? Then I think it's mostly just the prerelease testing to do and then we're ready for the splash.

**Comment by selaux** [comment]
What is to be done for #448? Is there a problem with the fix?

**Comment by Manuel-K** [comment]
I haven't found anything suspicious

**Comment by lynxlynxlynx** [comment]
It's more of a design decision. Leaving the implicit default is bad form.

**Comment by Manuel-K** [comment]
Ah. You are talking about #488.

**Comment by Manuel-K** [comment]
My suggestion: #635

**Comment by lynxlynxlynx** [comment]
Yeah, wrong id, sorry.

**Comment by selaux** [comment]
Allright. Release packages have been built and attached to the release: https://github.com/ja2-stracciatella/ja2-stracciatella/releases/tag/v0.16.0

Now for testing...

**Comment by selaux** [comment]
Tested a release build on Linux (unfortunately not the .deb package because of slow internet). Except for the fixed AP bug, I didn't notice anything...

**Comment by selaux** [comment]
@JAsmine-ja2 You did some testing on Windows, correct?

**Comment by selaux** [comment]
Attached new builds to release.

**Comment by JAsmine-ja2** [comment]
Yes, I tested on Windows. I played a campaign for severaly days (game days). Conquered Drassen, the SAM site in D15. Got Skyrider, did the food quest and stuff.

**Comment by lynxlynxlynx** [comment]
Haven't managed to play yet, but I did the remaining updates to the website (how to run page) and realised we forgot something: #651

**Comment by selaux** [comment]
As there is no one to test on macOS, imho we could publish the release. I tested basic execution on a friends machine on macOS but could not do comprehensive testing...

**Comment by Manuel-K** [comment]
It would be nice if we could make the release this year. ;-)

**Comment by selaux** [comment]
Didn't make it this year but new years is also a nice time for a release 🙂 . I added the announcement to the webpage.

**Comment by lynxlynxlynx** [comment]
Announced on the forum. @JAsmine-ja2, please handle Moddb. And we're done. :v:

**Comment by JAsmine-ja2** [comment]
> Announced on the forum. @JAsmine-ja2, please handle Moddb. And we're done. ✌️

Done. The news article might take some time to get authorized.

[http://www.moddb.com/mods/ja2-stracciatella]

**Comment by lynxlynxlynx** [comment]
Thanks, closing. Good job everyone!

**Comment by lynxlynxlynx** [comment]
Some nice extra coverage:
https://www.gamingonlinux.com/articles/the-ja2-stracciatella-game-engine-for-jagged-alliance-2-has-a-new-major-release.10991
