### ISSUE TITLE
0.17 checklist

### ISSUE THREAD

**Issue by lynxlynxlynx** [ja2-stracciatella/ja2-stracciatella#654]
Just a copy from 0.16 to be adapted as we go.

- [x] Fix or postpone issues in the [milestone](https://github.com/ja2-stracciatella/ja2-stracciatella/milestone/4)
- [x] Decide if 0.17 should be 1.0 #443 
- [x] Triage open pull requests
- [x] Finalise choice of version number
- [x] Update Version number
- [x] Github prerelease and tags
- [x] Attach built versions to release
  - [x] Linux, Windows
  - [x] OS X
- [ ] Runtime tests of release packages
  - [x] Linux
    - [x] Ubuntu 20.04 x64
  - [x] Windows
  - [ ] OS X
- [x] Add new contributors to contributors.txt #1151 
- [x] Update changes.md #1153
- [x] Document new features
  - [x] https://ja2-stracciatella.github.io/features/
    - WF done
    - change launcher screenshot + add any missing text https://github.com/ja2-stracciatella/ja2-stracciatella/pull/840
    - multiple mod support is launcher only
    - remove "currently impossible from the launcher"
  - [x] https://ja2-stracciatella.github.io/how-to-run/#extra-configuration-and-modding
    - mention location is given by the launcher
    - explain the way it can be overriden 
    - mention Night Ops, PCM, single download of all external mods
https://github.com/ja2-stracciatella/ja2-stracciatella/issues/707#issuecomment-650677939
- [x] Make prerelase the release
- [x] reset version to +1-dev
- [ ] Announce
  - [x] Write main announcement
  - [x] Website
  - [x] Bears pit
  - [ ] Moddb

WIP announcement
---
layout: post
title: Release 0.17.0
---

The Jagged Alliance 2 Stracciatella team is proud to present a new release. Over two years in the making, it includes several new features, plenty of bugfixes compared to previous versions and the original game, more work in externalizing data and innumerable clean-ups of the old code base. Also notable is the better launcher experience and easier tweaking of settings for power users and modders.

Through 1517 commits at least 61 bugs were fixed, 28 of which affect vanilla.

__New Features__:

- A redesigned [graphical launcher](https://ja2-stracciatella.github.io/#gui-launcher) with more toggles, multiple mod support and the location of the main settings file (game.json)
- Data files are now searched for in several places and more easily overriden LINK
- Several hardcoded values and assumptions are now externalized to json files for easy editing
- Basic Wildfire and Night Ops support LINKME
- Several new standalone optional [mini-mods](https://ja2-stracciatella.github.io/#bundled-optional-mini-mods) 
- The map editor now works out of the box, using bundled dummy icons
- Several smaller features like IMP import and better screen scaling options

We are shipping pre-built packages for Ubuntu, Windows and OS X. This should help users to easily get started with Jagged Alliance 2 Stracciatella. For users willing to take a risk we also provide automatically created [nightly builds](http://builds-ja2.stefanlau.com/nightlies/).

__Download__:
[http://ja2-stracciatella.github.io/download/](http://ja2-stracciatella.github.io/download/)
Make sure to uninstall any previous versions before installing.

__Build changes__:
 - a C++11 compatible compiler is now required
 - Dependency on boost has been removed
 - New dependency: string theory, a string library (also bundled in the repo)

_Warning_: **SDL2 2.0.6 on Linux**  has a fatal bug in the audio conversion code. As a workaround, the game automatically disables all sounds if it detects this version during startup. Please downgrade to version 2.0.5 or use **version 2.0.7 or later**.

__Main Changelog__:
<copy changes.md snippet> +1 vanilla

**Comment by flaviojs** [comment]
How about updating the crate version (rust code) to match the release version too? `Cargo.toml` has 0.1.0 right now.

**Comment by selaux** [comment]
As we don't publish the crate, I don't see a big advantage, but I'm also not against it :wink:.

On another topic I think it makes sense to do a release soon, as we currenltly have a bunch of changes on master that have not been tested by the broad public...

**Comment by lynxlynxlynx** [comment]
I'm not opposed to a release. I have to finish the -Wall PR, so it can get merged and one bug about -mod that's not in the milestone, but I think that's it from my side.

**Comment by flaviojs** [comment]
There is no clear indication as to when a release should be made.
How about starting to impose a 1-year limit? As long as there are changes, a release is made (minor or major, doesn't matter).

**Comment by lynxlynxlynx** [comment]
I'm not sure it would help much. It seems the known regressions from this development cycle have been taken care of, so we can move ahead with 0.17.

**Comment by ja2-derek** [comment]
It's been just over 2 years since the last release! It looks like the issues under the 0.17 milestone have been addressed, except AP-related ones. Maybe postpone those and move ahead?

**Comment by lynxlynxlynx** [comment]
There's one with several issues partly about the launcher (game.json one), but it could be postponed too. It's mostly about finishing the dev work, eg. all the thankless refactoring Flávio has been doing, cleaning up the PR list and then testing thoroughly through gameplay.

@flaviojs Do you want to finish all the string theory stuff first?

There's also some easily mergable janitorial stuff from #1002, maybe also some chocolate bits (but it defintiely contains too much).

**Comment by flaviojs** [comment]
Go ahead and release, don't wait for my string stuff.

**Comment by ja2-derek** [comment]
Are we all set for 0.17?

**Comment by lynxlynxlynx** [comment]
I hoped Flavio would have finished #1056 by now, but he's probably enjoying some well deserved vacation. Same with some unfinished 1.13 goodies from vvx. Not really release blockers though.

 It would be good to get the last issue in the milestone finished: #707. We keep adding settings, so it's just getting more pressing as time goes on. Not sure if anything remains to do actually, need to read it slowly. From a glance it seems like we can already handle the file in (stracciatella_home)/externalized/game.json, at least for installed setups (not sure how it resolves for running out of the build dir).

**Comment by ja2-derek** [comment]
Should we start the 0.17.x branch? 

I have been started testing master (I mean playing the game) and waiting for the release candidate. I have been avoiding non-bugfix changes recently, e.g. #1128, #665, #148, which I think are not necessary for 0.17. I want 0.17 to be the most stable version of Stracc ever.

If there are only a couple of remaining open issues, we can start the branch, and later on port those fixes back when finished.

**Comment by lynxlynxlynx** [comment]
Yeah, I was just waiting for myself to clean up vvx's goodies, but I can also split the PR and leave the imp stuff for later. Will take a look today.

**Comment by lynxlynxlynx** [comment]
Ok, let's do it. :) I'll go start on the janitorial stuff of the second half of the list.

**Comment by ja2-derek** [comment]
I can't wait to see how long the changelog is...

**Comment by lynxlynxlynx** [comment]
Added a draft announcement for the website, please take a look if all looks well. Particularly not certain about the multiple mod support (launcher screenshots show a checkbox field) and if I got the point of the free editor.slf correctly.

Will add more links etc. as the main docs get updated.

**Comment by ja2-derek** [comment]
Where can I see the draft? Don't seem to see any new commits in the github.io repo.

Just wondering if we should mention how to upgrade from 0.16 - in particular the new externalization JSON must be copied over, as well as the new dicts in `game.json`.

**Comment by ja2-derek** [comment]
Trying to think a non-technical player's perspective:

- editor.slf - maybe something like: Map editor now works out of the box, using the bundled dummy icons.
- We may need a section in the main docs about data directories, and how to customize the game.
- Externalization effort mostly for modders
- SDL version problem only affects Linux.

**Comment by lynxlynxlynx** [comment]
Thanks, improved it with your feedback.

Re upgrade:
- I doubt anyone has overridden the default game.json, but even if so, with the fallbacks in place, the old ones should work as fine
- externalized json: also don't see a problem; it could only break if people just grabbed the exe from the archive and nothing else, which is an odd thing to do. Or am I missing something?

**Comment by ja2-derek** [comment]
>* I doubt anyone has overridden the default game.json, but even if so, with the fallbacks in place, the old ones should work as fine

The old JSON do not have the `"progress"` section and will fail. Does it not? But not a problem if we agree on the next point
 
>* externalized json: also don't see a problem; it could only break if people just grabbed the exe from the archive and nothing else, which is an odd thing to do. Or am I missing something?

You should be right.. but that's what I keep doing lol

**Comment by lynxlynxlynx** [comment]
Hmm, true. Added warning:
> Make sure to uninstall any previous versions before installing.

**Comment by lynxlynxlynx** [comment]
Ok, website updates done, except:
- news not posted — obviously waiting for the actual release
- I was writing from memory, is it correct that game.json has to be in data/ to be found? https://ja2-stracciatella.github.io/how-to-run/#extra-configuration-and-modding
- still need to update launcher pics

And the pics are too big, I'll try reorganizing the features page somehow. I'll also do the minimal test soon, but thanks Derek for already giving it a thorough look.

**Comment by ja2-derek** [comment]
Correct. It's expected at $HOME/.ja2/data.game.json or %Documents%\JA2\data\game.json

**Comment by ja2-derek** [comment]
And also thanks to you @lynxlynxlynx for all the hard work to close out the release!

**Comment by lynxlynxlynx** [comment]
I reran the failing builds (editor.slf), however the builds still aren't up. It also looks like nightlies aren't being uploaded again:
http://builds-ja2.stefanlau.com/nightlies/
Any idea @selaux ?

**Comment by selaux** [comment]
They should be in the `releases` folder here: https://storage.googleapis.com/ja2-builds/index.html. But it seems appveyor still pushed them to the wrong folder (called `true`). I pushed a fix to master and updated the tag, so they should be there soon.

PS: I also updated the link for nightlies on the website, so it points to that url.

**Comment by lynxlynxlynx** [comment]
Ah, forgot about that. Derek fixed another regression and we're currently investigating this fresh report on the forum:
http://thepit.ja-galaxy-forum.com/index.php?t=msg&goto=360622

So we'll have to retag. I guess we should be tagging as -rc next time, until we're finally happy and ready to release.

**Comment by lynxlynxlynx** [comment]
Tried the current 0.17.0 deb and it works fine. Ran the updated launcher for the first time and updated the docs. Meaning all the tedium is done. :)

**Comment by selaux** [comment]
Did a playthrough til Drassen with the 0.17.0 deb and except the one issue with the launcher (#1160) saw nothing out of the ordinary.

**Comment by selaux** [comment]
macOS version works fine as well, except for #1160. Didn't do the full playthrough til the end of Drassen though.

**Comment by lynxlynxlynx** [comment]
Ok, so the unplanned rc phase was successful — in the sense that we avoided some avoidable problems. So it's time to retag, release and publish. I'll let @selaux do it, since he's the Master of builds, then we do a last quick test and I'll spam the rest. :)

**Comment by selaux** [comment]
Tag is updated. Builds should be there soon.

**Comment by ja2-derek** [comment]
Builds are up - https://storage.googleapis.com/ja2-builds/index.html#releases/v0.17.0/

**Comment by ja2-derek** [comment]
Tested thet VC 64-bit build on Win 10. Played till Bobby Ray delivered to Drassen without issues.

But the "guess game version" button printed several lines of log then froze. I killed the process after 30 minutes.

**Comment by selaux** [comment]
So is this a non issue, or should we fix it?

**Comment by ja2-derek** [comment]
There are no other reports of this issue, and it has been the same all the time. So I would say it's non-issue.

I do have a fix/workaround for it, but maybe for 0.18.

**Comment by ja2-derek** [comment]
So we've just merged 3 PRs for usability. What's the plan now?

1. Go ahead with existing 0.17.0 tag, leave those commits to next version; or
2. Re-tag 0.17.0 and re-test; or
3. Mark 0.17.0 as pre-release and create new tag 0.17.1. Re-test and release 0.17.1 directly

**Comment by lynxlynxlynx** [comment]
It's a fix, so why leave it hanging — I'm for retagging.

**Comment by selaux** [comment]
Retagged.

**Comment by lynxlynxlynx** [comment]
I tried the amd64 build and played until clearing the first sector. All fine and well, as expected. Can one of you give one of the windows builds a spin? I think we're then set.

**Comment by ja2-derek** [comment]
Just tried the Win32 build  (ja2-stracciatella_0.17.0+1e6667a_win-msvc32-140.zip). Played till rebel basement. Everything looks fine.

**Comment by lynxlynxlynx** [comment]
Great, I'll start updating the website.

**Comment by JAsmine-ja2** [comment]
Unfortunally, I won't have time to take care of the moddb page.
The "company" set up in moddb is a dummy and there's only me in it.
I can invite you on moddb or via mail to join the "company".

And more importantly: **Congratulations everyone on the nice progress !!!!**

**Comment by lynxlynxlynx** [comment]
Yeah, I guess it doesn't hurt to have updated info there. My username there is mokovec, thanks.

**Comment by JAsmine-ja2** [comment]
> Yeah, I guess it doesn't hurt to have updated info there. My username there is mokovec, thanks.

I sent you an invitation on moddb.

**Comment by lynxlynxlynx** [comment]
Thanks, it seems to have worked and after quite some time I managed to find where one can post (what a poor ui).

**Comment by JAsmine-ja2** [comment]
> (what a poor ui)
very true :(
maybe I can add the new packages to the mod's download page on moddb.

**Comment by lynxlynxlynx** [comment]
If I'm not too late: there is no need, it is easier for us to have a central download place.
