### ISSUE TITLE
Externalizing game data

### ISSUE THREAD

**Issue by JAsmine-ja2** [ja2-stracciatella/ja2-stracciatella#665]
Externalizing game data is definitely one of the most important parts of the "modding platform" aspect of the Stracciatella project.

### System
- [x] new hotkeys
- [x] stat progress bar in GUI
- [x] item shadows
- [x] game speed aka milliseconds per game cycle
### General gameplay settings
- [x] starting cash
- [x] drop all
- [x] always reveal all drops, regardless of distance
- [x] CtH settings
- [x] stealing/losing deliveries at Drassen airport
- [x] manually start turn-based mode
- [x] extra attachments on armor
- [x] elite soldier EXP level
- [x] min status % of items in enemy hands
- [x] minor AI improvements
- [x] enable multiple interrupts

### System
- [x] **music** - this feature (#387) is not clearly documented. Issues remain (#664).
### IMP creation
- [x] **IMP starting inventory** - extra items for skills and traits aren't externalized
- [x] **IMP creation attribute points** - works, but has issues (#644)
### Items
- [x] **ammo types** - can't be edited
- [x] **weapons** - number of indices can't be increased
- [x] **magazines** - number of indices can't be increased

### Army
- [ ] garrison groups (permanent presence in certain sectors)
- [ ] patrol groups (mobile squads moving around)
- [ ] army composition (details on the groups like number and probability of being replaced)

### Mapping:
- [ ] sector names
- [ ] sector loadscreens
- [ ] cities (location, size, name ...)
- [ ] movement costs (moving from one sector to another)
- [ ] accessibility of setors ("borderland", ocean, "bad sectors"...)
- [ ] SAM sites (sector, location of the computer)
- [ ] air control table (the area that is defended by each SAM site)
- [ ] BR shipping destination
- [ ] Bloodcats (sectors, number, chance to encounter)
- [ ] Coolness (per sector)
- [ ] underground sectors (increase max. no.)

### Items:
- [ ] armor
- [ ] other items
- [ ] attachments (increase max. no.)
- [ ] items, that are always available regardless of their coolness vs player's progress (#173)

### Misc. stuff:
- [ ] delivery methods of BR (cost, time)
- [ ] chopper refuelling stations / bases
- [ ] Possibility to increase stats with lvl 0 (zero)
- [ ] No. of mercs (AIM, MERC) that can die while "on assignment" per difficulty
- [ ] Progress %'s when Madlab, Mike and Iggy are made available
- [ ] Dialogues
- [ ] Merc profiles (for all mercs and npcs)

**Comment by lynxlynxlynx** [comment]
I'm not sure it's important, but this list is conflating game data, game logic and new features.

**Comment by ja2-derek** [comment]
A couple things to be externalized:

- Mines (type, location, production rate)
- Soldier creation (colors, attribute stats)

**Comment by lynxlynxlynx** [comment]
Looking at momoko's PR showed another candidate set: tileset data: https://github.com/ja2-stracciatella/ja2-stracciatella/blob/master/src/game/TileEngine/WorldDat.cc#L74

The simplest way would be to externalize an index to represent the function to use, but considering all are mostly the same (only roads and floors differ), we could just externalize all the properties or all the differing ones.
