### ISSUE TITLE
Bloodcat / ambush issues

### ISSUE THREAD

**Issue by JAsmine-ja2** [ja2-stracciatella/ja2-stracciatella#686]
### Problems with Bloodcats in general and BC ambushes

- [x] BC's can't be damaged with ALT+O cheat - **reported** here: #126 , **fixed** here: #583
- [ ] BC's are passive when ambushing the player - first reported here: #126 , supposedly fixed here: #584 , nevertheless still present in 0.16.0 !!
- [ ] Player can compress time or move the squad on the strategic map while being ambushed by BC's - **reported** here: #412
